# Generated by Django 6.1.1 on 2026-09-08 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0006_historialordenproduccion_detalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_anterior', models.CharField(blank=True, max_length=120)),
                ('referencia_anterior', models.CharField(blank=True, max_length=120)),
                ('lote_actual', models.CharField(blank=True, max_length=120)),
                ('referencia_actual', models.CharField(max_length=120)),
                ('nombre_operario', models.CharField(blank=True, max_length=120)),
                ('productos_retirados', models.BooleanField(blank=True, null=True)),
                ('sin_restos_lote_anterior', models.BooleanField(blank=True, null=True)),
                ('balanzas_limpias', models.BooleanField(blank=True, null=True)),
                ('superficies_limpias', models.BooleanField(blank=True, null=True)),
                ('utensilios_limpios', models.BooleanField(blank=True, null=True)),
                ('piso_limpio', models.BooleanField(blank=True, null=True)),
                ('area_ordenada', models.BooleanField(blank=True, null=True)),
                ('bolsa_identificada', models.BooleanField(blank=True, null=True)),
                ('epp_adecuado', models.BooleanField(blank=True, null=True)),
                ('residuos_dispuestos', models.BooleanField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio_supervision', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('revision', models.CharField(blank=True, choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('devuelta', 'Devuelta a Pesaje')], max_length=12)),
                ('motivo_devolucion', models.TextField(blank=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesaje', to='produccion.ordenproduccion')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesajes_registrados', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesajes_revisados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_real', models.DecimalField(decimal_places=4, max_digits=14)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.materialorden')),
                ('pesaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='pesaje.registropesaje')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pesaje', 'material'), name='peso_material_unico'), models.CheckConstraint(condition=models.Q(('peso_real__gt', 0)), name='peso_real_positivo')],
            },
        ),
    ]
