# Generated by Django 6.1.1 on 2026-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropesaje',
            name='critico_ambiente_adecuado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_area_equipos_limpios',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_cero_pellets',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_equipos_aptos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_liberacion_autorizada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_limpieza_anterior_liberada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_mp_identificadas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_sin_actividades_simultaneas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_sin_condiciones_inseguras',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropesaje',
            name='critico_uniforme_epp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
