# Generated by Django 6.0.3 on 2026-09-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0002_registropesaje_critico_ambiente_adecuado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropesaje',
            name='fecha_inicio_pesaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
