# Generated by Django 6.1.1 on 2026-09-07 18:53
"""
Agrega el rol 'Producción', distinto del genérico 'Personal de Planta':
solo Producción debe consultar/diligenciar Órdenes de Producción, no las
demás estaciones (Pesaje, etc.) que hoy comparten el rol 'planta'.

Reasigna la cuenta existente 'produccion' (creada con rol 'planta', antes
de que este rol propio existiera) a 'produccion'. No toca otras cuentas
'planta' (ej. pesaje1/pesaje2).
"""

from django.db import migrations, models


def reasignar_usuario_produccion(apps, schema_editor):
    CustomUser = apps.get_model('usuarios', 'CustomUser')
    CustomUser.objects.filter(username='produccion', rol='planta').update(rol='produccion')


def revertir_usuario_produccion(apps, schema_editor):
    CustomUser = apps.get_model('usuarios', 'CustomUser')
    CustomUser.objects.filter(username='produccion', rol='produccion').update(rol='planta')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_registroauditoriausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('produccion', 'Producción'), ('planta', 'Personal de Planta')], default='planta', max_length=20),
        ),
        migrations.RunPython(reasignar_usuario_produccion, revertir_usuario_produccion),
    ]
