# Generated by Django 6.1.1 on 2026-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('produccion', 'Producción'), ('picky', 'Picky'), ('pesaje', 'Pesaje'), ('mezcla', 'Mezcla'), ('extrusion', 'Extrusión'), ('calidad', 'Calidad'), ('empaque', 'Empaque'), ('planta', 'Personal de Planta')], default='planta', max_length=20),
        ),
    ]
