# Generated by Django 6.1.1 on 2026-09-08 19:45
"""
Quita el rol 'supervisor_pesaje': por ahora la revisión del pesaje la hace
el rol 'supervisor' genérico, sin distinguir el área (Pesaje, Mezcla, etc.).

Cualquier cuenta que ya tuviera ese rol pasa a 'supervisor', para que no
quede con un valor huérfano y sin permisos.
"""

from django.db import migrations, models


def convertir_a_supervisor(apps, schema_editor):
    CustomUser = apps.get_model('usuarios', 'CustomUser')
    CustomUser.objects.filter(rol='supervisor_pesaje').update(rol='supervisor')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_customuser_rol'),
    ]

    operations = [
        migrations.RunPython(convertir_a_supervisor, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('produccion', 'Producción'), ('picky', 'Picky'), ('pesaje', 'Pesaje'), ('mezcla', 'Mezcla'), ('extrusion', 'Extrusión'), ('calidad', 'Calidad'), ('empaque', 'Empaque'), ('planta', 'Personal de Planta')], default='planta', max_length=20),
        ),
    ]
