# Generated by Django 6.1.1 on 2026-09-07 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('producto', models.CharField(max_length=120)),
                ('cantidad', models.FloatField()),
                ('materia_prima', models.CharField(max_length=120)),
                ('urgente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('planeacion', 'Planeación'), ('picky', 'Picky'), ('pesaje', 'Pesaje'), ('mezcla', 'Mezcla'), ('extrusion', 'Extrusión'), ('calidad', 'Calidad'), ('empaque', 'Empaque'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='planeacion', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Historial de Orden de Producción',
                'verbose_name_plural': 'Historial de Órdenes de Producción',
                'ordering': ['-fecha'],
            },
        ),
    ]
