# Generated by Django 6.1.1 on 2026-09-07 17:57

from django.db import migrations, models


def migrar_urgente_a_clasificacion(apps, schema_editor):
    """Preserva el dato existente: urgente=True -> clasificacion='urgente'."""
    OrdenProduccion = apps.get_model('produccion', 'OrdenProduccion')
    OrdenProduccion.objects.filter(urgente=True).update(clasificacion='urgente')


def revertir_clasificacion_a_urgente(apps, schema_editor):
    OrdenProduccion = apps.get_model('produccion', 'OrdenProduccion')
    OrdenProduccion.objects.filter(clasificacion='urgente').update(urgente=True)


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='clasificacion',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('peligroso', 'Producto peligroso'), ('normal', 'Proceso normal')], default='normal', max_length=20),
        ),
        migrations.RunPython(migrar_urgente_a_clasificacion, revertir_clasificacion_a_urgente),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='urgente',
        ),
    ]
