# Generated by Django 6.1.1 on 2026-09-07 18:34
"""
Reestructura OrdenProduccion para reflejar los campos reales del
documento físico de Sumicolor (ver DiccionarioDatos_OP.xlsx /
BD_TABLAS_OP_HP.xlsx) y crea MaterialOrden para el desglose de materiales,
en reemplazo de los campos de texto libre 'producto' y 'materia_prima'.

Los campos nuevos que Sumicolor marca como "not null" (codigo_producto,
codigo_cliente, pedido, vencimiento_pedido) se agregan sin valor por
defecto: al momento de escribir esta migración la tabla OrdenProduccion
está vacía (verificado), así que no hay filas existentes que respaldar
para esas columnas. El RunPython de abajo sí preserva cualquier dato que
pudiera existir en 'producto'/'materia_prima'.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrar_producto_y_materia_prima(apps, schema_editor):
    OrdenProduccion = apps.get_model('produccion', 'OrdenProduccion')
    MaterialOrden = apps.get_model('produccion', 'MaterialOrden')

    for orden in OrdenProduccion.objects.all():
        orden.referencia = orden.producto or ''
        orden.save(update_fields=['referencia'])
        if orden.materia_prima:
            MaterialOrden.objects.create(
                orden=orden,
                codigo='',
                descripcion=orden.materia_prima,
                porcentaje=100,
                cantidad=orden.cantidad,
                localizacion='',
            )


def revertir_referencia_y_materiales(apps, schema_editor):
    OrdenProduccion = apps.get_model('produccion', 'OrdenProduccion')
    for orden in OrdenProduccion.objects.all():
        orden.producto = orden.referencia
        orden.save(update_fields=['producto'])
        primer_material = orden.materiales.first()
        if primer_material:
            orden.materia_prima = primer_material.descripcion
            orden.save(update_fields=['materia_prima'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0002_remove_ordenproduccion_urgente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='codigo_producto',
            field=models.CharField(default='', max_length=20, verbose_name='código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='referencia',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='codigo_cliente',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='pedido',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_pedido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='hora_pedido',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='vencimiento_pedido',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_hora_lote',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='creado_por',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ordenes_creadas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='MaterialOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=120)),
                ('porcentaje', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('localizacion', models.CharField(blank=True, max_length=120)),
                (
                    'orden',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='materiales',
                        to='produccion.ordenproduccion',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Material de Orden de Producción',
                'verbose_name_plural': 'Materiales de Orden de Producción',
            },
        ),
        migrations.RunPython(migrar_producto_y_materia_prima, revertir_referencia_y_materiales),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='materia_prima',
        ),
    ]
