# Generated by Django 6.1.1 on 2026-09-07 20:35
"""
Liberación Producción → Picky: agrega la trazabilidad de la transición
(fecha de envío, operario que recibe en Picky, cuenta y fecha de
recepción) y renombra el estado 'planeacion' a 'produccion', para que la
etapa se llame igual que la app y el rol correspondientes.

El renombre conserva las OP existentes: se actualiza el valor de las
filas antes de cambiar los choices del campo.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def renombrar_planeacion_a_produccion(apps, schema_editor):
    OrdenProduccion = apps.get_model('produccion', 'OrdenProduccion')
    Historial = apps.get_model('produccion', 'HistorialOrdenProduccion')
    OrdenProduccion.objects.filter(estado='planeacion').update(estado='produccion')
    Historial.objects.filter(campo='estado', valor_anterior='planeacion').update(
        valor_anterior='produccion'
    )
    Historial.objects.filter(campo='estado', valor_nuevo='planeacion').update(
        valor_nuevo='produccion'
    )


def revertir_produccion_a_planeacion(apps, schema_editor):
    OrdenProduccion = apps.get_model('produccion', 'OrdenProduccion')
    Historial = apps.get_model('produccion', 'HistorialOrdenProduccion')
    OrdenProduccion.objects.filter(estado='produccion').update(estado='planeacion')
    Historial.objects.filter(campo='estado', valor_anterior='produccion').update(
        valor_anterior='planeacion'
    )
    Historial.objects.filter(campo='estado', valor_nuevo='produccion').update(
        valor_nuevo='planeacion'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_reestructurar_op_datos_reales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            renombrar_planeacion_a_produccion, revertir_produccion_a_planeacion
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_envio_picky',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_recepcion_picky',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='nombre_operario_picky',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='recibida_por_picky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas_picky', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('produccion', 'En Producción'), ('picky', 'En Picky'), ('pesaje', 'En Pesaje'), ('mezcla', 'En Mezcla'), ('extrusion', 'En Extrusión'), ('calidad', 'En Calidad'), ('empaque', 'En Empaque'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='produccion', max_length=20),
        ),
    ]
