# Generated by Django 6.1.1 on 2026-09-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_liberacion_picky'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_envio_pesaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
