# Generated by Django 6.1.1 on 2026-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_liberacion_pesaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialordenproduccion',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('produccion', 'En Producción'), ('picky', 'En Picky'), ('pesaje', 'En Pesaje'), ('supervision_pesaje', 'En supervisión de Pesaje'), ('mezcla', 'En Mezcla'), ('extrusion', 'En Extrusión'), ('calidad', 'En Calidad'), ('empaque', 'En Empaque'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='produccion', max_length=20),
        ),
    ]
