# Generated by Django 6.1.1 on 2026-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_historialordenproduccion_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='grupo_critico_pesaje',
            field=models.CharField(blank=True, choices=[('', 'Sin clasificar'), ('no_critico', 'No crítico'), ('blancos', 'Blancos'), ('aditivos_retardantes', 'Aditivos / Retardantes a la Llama'), ('hojas_azules', 'Hojas azules')], default='', help_text='Clasificar según el código de producto y su ficha técnica. Obligatorio antes de enviar Pesaje a supervisión.', max_length=20),
        ),
    ]
